version: 2

sources:
  - name: conformed
    database: dw001
    schema: conformed
    tables:
      - name: okr__user
      - name: okr__team
      - name: okr__team_users_user
      - name: amplitude__events

models:
  - name: dim__user
    columns:
      - name: id
      - name: last_access_time

  - name: dim__company
    columns:
      - name: id
      - name: name
      - name: type

  - name: fct__user_accesses
    columns:
      - name: user_id
      - name: access_time

  - name: fct__user_teams
    columns:
      - name: user_id
      - name: team_id
