version: 2

sources:
  - name: conformed
    database: dw001
    schema: conformed
    tables:
      - name: okr__user
      - name: amplitude__events

models:
  - name: dim__user
    columns:
      - name: id
      - name: last_access_time

  - name: fct__user_accesses
    columns:
      - name: user_id
      - name: access_time
