version: 2

sources:
  - name: conformed
    database: dw001
    schema: conformed
    tables:
      - name: okr__user
      - name: okr__team
      - name: okr__team_users_user
      - name: okr__cycle
      - name: okr__objective
      - name: okr__key_result
      - name: amplitude__events

models:
  - name: dim__user
    columns:
      - name: id
      - name: role
      - name: about
      - name: email
      - name: gender
      - name: picture
      - name: nickname
      - name: authz_sub
      - name: first_name
      - name: last_name
      - name: linked_in_profile_address
      - name: created_at
      - name: updated_at
      - name: last_access_time
      - name: type

  - name: dim__team
    columns:
      - name: id
      - name: name
      - name: gender
      - name: owner_id
      - name: parent_id
      - name: description
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__company
    columns:
      - name: id
      - name: type

  - name: dim__cycle
    columns:
      - name: id
      - name: active
      - name: period
      - name: cadence
      - name: team_id
      - name: date_start
      - name: date_end
      - name: parent_id
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: dim__objective
    columns:
      - name: id
      - name: title
      - name: team_id
      - name: cycle_id
      - name: owner_id
      - name: created_at
      - name: updated_at
      - name: company_id

  - name: fct__user_accesses
    columns:
      - name: user_id
      - name: access_time

  - name: fct__user_teams
    columns:
      - name: user_id
      - name: team_id

  - name: fct__user_companies
    columns:
      - name: user_id
      - name: company_id
