---
kind: Service
apiVersion: v1
metadata:
  name: analytics-canary
  labels:
    app.kubernetes.io/name: analytics-canary
    app.kubernetes.io/part-of: analytics
    app.kubernetes.io/component: service
    app.kubernetes.io/version: 1.0.0
  annotations:
    mesh.traefik.io/traffic-type: "tcp"
spec:
  selector:
    app.kubernetes.io/name: analytics-canary
  ports:
    - name: tcp
      port: 8080
      targetPort: 9090
      protocol: TCP
