---
kind: Service
apiVersion: v1
metadata:
  name: analytics-canary
  labels:
    app.kubernetes.io/name: analytics-canary
    app.kubernetes.io/part-of: analytics
    app.kubernetes.io/component: service
    app.kubernetes.io/version: 1.0.0
spec:
  sessionAffinity: None
  clusterIP: None
  selector:
    app: test
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
